package com.fivepotato.eggmeetserver.domain.mentoring;

public enum Category {
    IT_WEB,
    IT_BACKEND,
    IT_APP,
    IT_GAME,
    IT_DEVOPS,
    IT_MACHINE_LEARNING,
    IT_DATA_ANALYSIS,
    IT_PROGRAMING_LANGUAGE,
    IT_ETC,

    LANGUAGE_ENGLISH,
    LANGUAGE_JAPANESE,
    LANGUAGE_CHINESE,
    LANGUAGE_SPANISH,
    LANGUAGE_FRENCH,
    LANGUAGE_GERMAN,
    LANGUAGE_RUSSIAN,
    LANGUAGE_ARABIC,
    LANGUAGE_ITALIAN,
    LANGUAGE_ETC,

    JOB_EMPLOY,
    JOB_PAPER,
    JOB_SKILL,
    JOB_ETC,

    LICENSE_GOVERNMENT,
    LICENSE_ETC,

    MEDIA_EDIT,
    MEDIA_FILMING,
    MEDIA_CAMERA,
    MEDIA_ETC,

    DESIGN_ILLUSTRATION,
    DESIGN_CONCEPT_ART,
    DESIGN_EMOTICON,
    DESIGN_DRAWING,
    DESIGN_CALLIGRAPHY,
    DESIGN_TOOL,
    DESIGN_UIUX,
    DESIGN_VISUAL,
    DESIGN_ETC,

    MARKETING_DIGITAL,
    MARKETING_COPYRIGHTING,
    MARKETING_DATA,
    MARKETING_ETC,

    INVESTMENT_ACCOUNTING,
    INVESTMENT_STOCK,
    INVESTMENT_PROPERTY,
    INVESTMENT_ETC,

    MUSIC_THEORY,
    MUSIC_COMPOSITION,
    MUSIC_WRITING_LYRICS,
    MUSIC_ETC,

    EXPERIENCE_TRAVEL,
    EXPERIENCE_FOUNDATION,
    EXPERIENCE_FAIL,
    EXPERIENCE_EMPLOYMENT,
    EXPERIENCE_ETC
}
