package com.fivepotato.eggmeetserver.domain.user;

public enum Location {
    SEOUL_JONGRO_JUNGGU_YOUNGSAN,
    SEOUL_GANGNAM_SEOCHO_YANGZE,
    SEOUL_MAPO_SEODAEMUN_EUNPYEONG,

    GWANGJU_BUKGU,
    GWANGJU_SEOGU,
    GWANGJU_NAMDONGGU,
    GWANGJU_GWANGSANGU
}
