package com.fivepotato.eggmeetserver.domain.user;

public enum Location {
    ALL,

    SEOUL_JONGRO_JUNGGU_YOUNGSAN,
    SEOUL_GANGNAM_SEOCHO_YANGZE,
    SEOUL_MAPO_SEODAEMUN_EUNPYEONG,
    SEOUL_SONGPA_GANGDONG_ZAMSIL,
    SEOUL_DONGDAEMUN_JUNRANG_GWANGZIN_SEONGDONG,
    SEOUL_NOWON_DOBONG_GANGBUK_SEONGBUK,
    SEOUL_GANGSEO_YANGCHEON_GEUMCHEON,
    SEOUL_YEONGDEUNGPO_GURO_SINDORIM,
    SEOUL_DONGZAK_KWANAK_SADANG,

    GYEONGGI_SEONGNAM_BUNDANG_PANGYO,
    GYEONGGI_YEONGIN_ZUKZEON_SUJI,
    GYEONGGI_SUWON_YEONGTONG_GWANGGYO,
    GYEONGGI_ANYANG_GWACHEON_GUNPO_UIWANG,
    GYEONGGI_ANSAN,
    GYEONGGI_BUCHEON_GWANGMYEONG_SIHEUNG,
    GYEONGGI_HWASEONG_DONGTAN,
    GYEONGGI_OSAN_PYEONGTAEK_ANSUN,
    GYEONGGI_GURI_HANAM_NAMYANGJU,
    GYEONGGI_GAPYEONG_YANGPYEONG,
    GYEONGGI_GWANGJU_YICHEON_YEOJU,
    GYEONGGI_GOYANG_GIMPO_PAJU_ILSAN,
    GYEONGGI_UIJUNGBU_YANGJU_DONGDUCHEON,
    GYEONGGI_POCHEON_YEONCHEON,


    GYEONGBUK,
    GYEONGNAM,

    GWANGJU_BUKGU,
    GWANGJU_SEOGU,
    GWANGJU_NAMDONGGU_DONGGU,
    GWANGJU_GWANGSANGU
}
