package com.fivepotato.eggmeetserver.domain.user;

public enum Location {
    SEOUL_JONGRO_JUNGGU_YOUNGSAN,
    SEOUL_GANGNAM_SEOCHO_YANGZE,
    SEOUL_MAPO_SEODAEMUN_EUNPYEONG,
    SEOUL_SONGPA_GANGDONG_ZAMSIL,
    SEOUL_DONGDAEMUN_JUNRANG_GWANGZIN_SEONGDONG,
    SEOUL_NOWON_DOBONG_GANGBUK_SEONGBUK,
    SEOUL_GANGSEO_YANGCHEON_GEUMCHEON,
    SEOUL_YEONGDEUNGPO_GURO_SINDORIM,
    SEOUL_DONGZAK_KWANAK_SADANG,

    GWANGJU_BUKGU,
    GWANGJU_SEOGU,
    GWANGJU_NAMDONGGU,
    GWANGJU_GWANGSANGU
}
